### ISSUE TITLE
Spellcheck for Yellow MSG text

### ISSUE THREAD

**Issue by GS-Netz** [pltrant/GSL-Editor#14]
Is it possible to add spellcheck to our yellow colored msg text? Thanks. Chad/Netz

**Comment by pltrant** [comment]
This can be handled by a separate extension.  I came across [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).  Using it, we can create a custom configuration file to only check .*gsl files and only within specific regex patterns.  In addition, we can add custom words to the dictionary.

`{
    "version": "0.2",
    "files": ["*.gsl"],
    "words": [
        "Elanthia",
        "Lorminstra"
    ],
    "includeRegExpList": [
        "msg.*\".*\"",
        "set S\\d to \".*\"",
        "set T\\d to \".*\""
    ]
}`

Here's how it would look:

![image](https://user-images.githubusercontent.com/9040032/156399306-d41a7cb5-4829-471f-9685-0e6f9748e9d7.png)

You can then click on the lightbulb or right-click on the word to get suggestions, add it to the dictionary, etc.  We'd probably have to come up with some step-by-step instructions on how to install and configure the extension.

**Comment by pltrant** [comment]
This is now implemented as of version 1.9.1, but it must be manually enabled:

Add spellcheck to your code/comments by installing the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).  Follow the link, then click on the green Install button.  Next, open your Visual Studio Code Settings by hitting F1, then type in or copy/paste "Preferences: Open Settings (JSON)", and hit enter.  In the file, add this line `"cSpell.ignorePaths": []`, then save and close the file.
