### ISSUE TITLE
"GSL: List Tokens" Command has KaTeX ParseError

### ISSUE THREAD

**Issue by abirmingham** [pltrant/GSL-Editor#34]
**Steps to Reproduce**

1. Open vscode with GSL-Editor extension installed
2. `Ctrl+shift+p` to open command list
3. Execute command "GSL: List Tokens" ("Preview tokens.md" will open)
4. Scroll to bottom of "Preview tokens.md"

**Expected:** General tokens are shown
**Actual:** General tokens are not shown. Error is shown: `ParseError: KaTeX parse error: Can't use function '$' in math mode at position 22: …auses a single $̲ to be inserted…`

It looks like vscode [added KaTeX support](https://code.visualstudio.com/updates/v1_58#_math-formula-rendering-in-the-markdown-preview) in 1.58, which is perhaps when this issue was introduced. `$$` now indicates a math block. The solution is fairly straightforward - the `$$` token needs to be escaped.

**Screenshot**

<img width="334" alt="image" src="https://github.com/pltrant/GSL-Editor/assets/1661498/c82af860-33d6-4e5e-93a4-e59abd2235c7">

**Comment by abirmingham** [comment]
Once fixed, there seem to be some other issues in the markdown rendering:
<img width="425" alt="image" src="https://github.com/pltrant/GSL-Editor/assets/1661498/648bd570-c493-4df6-a2d1-624a9090260d">

I'm happy to open up an MR - just let me know if I should do so!

**Comment by pltrant** [comment]
Sure, submit a PR. Thanks!

**Comment by abirmingham** [comment]
Great, thanks Patrick. I'll go ahead and open a PR. Side note - I always forget that github calls them PRs and not MRs.

It looks like [vscode uses CommonMark](https://code.visualstudio.com/docs/languages/markdown#_does-vs-code-support-github-flavored-markdown), so I'll escape according to that specification. From that link: _"VS Code targets the [CommonMark](https://commonmark.org/) Markdown specification using the [markdown-it](https://github.com/markdown-it/markdown-it) library."_

**Comment by abirmingham** [comment]
Done! Hopefully I did that correctly, I've been in GitLab land for awhile.

There is a decision point described on the PR of whether to use backticks or escapes - happy to do either - just let me know. Thanks!
